### ISSUE TITLE
Colorblind-friendly colors and dark mode should not be married, they should be orthogonal

### ISSUE THREAD

**Issue by vorpal-buildbot** [silasary/Penny-Dreadful-Discord-Bot#13691]
needs some research but I can imagine one or more colorblind-friendly toggles? or do they have extensiions that do it better than we could anyway?

Reported on Discord by @bakert

**Comment by Tygrak** [comment]
I'd propose this for the colorblind colors.

```css
.mana-G {
    background-color: #0eff21;
}

.mana-R {
    background-color: #ff0c31;
}

.mana-B {
    background-color: #141414;
}

.mana-U {
    background-color: #006dce;
}

.mana-W {
    background-color: #fcfae8;
}
```


See this link to see the palette with a simulation of protanopia, deuternopia and tritanopia (basically the most severe forms of colorblindness, lighter forms of the same are called protanomaly, deuternomaly and tritanomaly). Do note that monochromacy does also exist, but I don't think there's a nice solution to accommodate it, the best solution would be to include the mana symbols, but there isn't enough space to do it in this context. Also monochromacy affects about 0.0033% of people, while dichromacy/anomalous trichromacy affects around 8% of people, so this should make things fully accessible for almost everyone.

https://davidmathlogic.com/colorblind/#%23252525-%23006DCE-%23FF0C31-%230EFF21-%23E8E8E8
(also for comparison here are the current colors: https://davidmathlogic.com/colorblind/#%23ACE2FA-%23CCC2C0-%23F8AA92-%239DD2AF-%23FFFCDA
-- note how for protanopia and deuternopia the black, red and green are extremely close -- the black and green look literally the same for deuternopia)

![Image](https://github.com/user-attachments/assets/2bba316b-b3ae-4c06-bfe5-c7884dddea7d)
